name: ensiklotari
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.1.0
  get: 4.6.5
  google_fonts: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: IkonEnsiklotari # the name of your font family
      fonts:
        - asset: fonts/IkonEnsiklotari.ttf # your font file name and the directory
